language: c
sudo: true
notifications:
  email: false
matrix:
    include:
        - os: osx
          compiler: gcc
          env: CXX=gcc
        - os: osx
          compiler: clang
          env: CXX=clang
script: make CC=$CXX
